export interface CustomerData {
  'Product ID [Non Editable]': string;
  'Variant ID [Non Editable]': string;
  'Product Type [Non Editable]': string;
  'Product Page': string;
  'Product URL': string;
  'Title': string;
  'Description': string;
  'SKU': string;
  'Option Name 1': string;
  'Option Value 1': string;
  'Option Name 2': string;
  'Option Value 2': string;
  'Option Name 3': string;
  'Option Value 3': string;
  'Option Name 4': string;
  'Option Value 4': string;
  'Option Name 5': string;
  'Option Value 5': string;
  'Option Name 6': string;
  'Option Value 6': string;
  'Price': string;
  'Sale Price': string;
  'On Sale': string;
  'Stock': string;
  'Categories': string;
  'Tags': string;
  'Weight': string;
  'Height': string;
  'Width': string;
  'Length': string;
  'Shipping Class': string;
  'Visibility': string;
  'Short Description': string;
  'Tax Status': string;
  'Tax Class': string;
  'Image': string;
  'Gallery': string;
  'Download Limit': string;
  'Download Expiry': string;
  'Parent': string;
  'Upsells': string;
  'Cross-sells': string;
  'External URL': string;
  'Button Text': string;
  'Meta: _wpsc_sku': string;
  'Meta: _wpsc_price': string;
  'Meta: _wpsc_product_metadata': string;
  'Meta: _wpsc_variation_id': string;
  'Meta: _wpsc_variation_data': string;
  'Meta: _wpsc_special_price': string;
  'Meta: _wpsc_display_on_front': string;
  'Meta: _wpsc_cache_hash': string;
  'Meta: _wpsc_is_donation': string;
  'Meta: _wpsc_donation_min_amount': string;
  'Meta: _wpsc_donation_max_amount': string;
  'Meta: _wpsc_donation_goal_amount': string;
  'Meta: _wpsc_donation_current_amount': string;
  'Meta: _wpsc_donation_campaign_end_date': string;
  'Meta: _wpsc_donation_campaign_start_date': string;
  'Meta: _wpsc_donation_campaign_status': string;
  'Meta: _wpsc_donation_campaign_progress': string;
  'Meta: _wpsc_donation_campaign_goal': string;
  'Meta: _wpsc_donation_campaign_donations': string;
  'Meta: _wpsc_donation_campaign_donor_count': string;
  'Meta: _wpsc_donation_campaign_description': string;
  'Meta: _wpsc_donation_campaign_title': string;
  'Meta: _wpsc_donation_campaign_image': string;
  'Meta: _wpsc_donation_campaign_video': string;
  'Meta: _wpsc_donation_campaign_category': string;
  'Meta: _wpsc_donation_campaign_tags': string;
  'Meta: _wpsc_donation_campaign_featured': string;
  'Meta: _wpsc_donation_campaign_sticky': string;
  'Meta: _wpsc_donation_campaign_order': string;
  'Meta: _wpsc_donation_campaign_visibility': string;
  'Meta: _wpsc_donation_campaign_password': string;
  'Meta: _wpsc_donation_campaign_excerpt': string;
  'Meta: _wpsc_donation_campaign_content': string;
  'Meta: _wpsc_donation_campaign_author': string;
  'Meta: _wpsc_donation_campaign_date': string;
  'Meta: _wpsc_donation_campaign_modified': string;
  'Meta: _wpsc_donation_campaign_parent': string;
  'Meta: _wpsc_donation_campaign_menu_order': string;
  'Meta: _wpsc_donation_campaign_type': string;
  'Meta: _wpsc_donation_campaign_mime_type': string;
  'Meta: _wpsc_donation_campaign_comment_status': string;
  'Meta: _wpsc_donation_campaign_comment_count': string;
  'Meta: _wpsc_donation_campaign_ping_status': string;
  'Meta: _wpsc_donation_campaign_to_ping': string;
  'Meta: _wpsc_donation_campaign_pinged': string;
  'Meta: _wpsc_donation_campaign_guid': string;
  'Meta: _wpsc_donation_campaign_post_status': string;
  'Meta: _wpsc_donation_campaign_post_name': string;
  'Meta: _wpsc_donation_campaign_post_password': string;
  'Meta: _wpsc_donation_campaign_post_excerpt': string;
  'Meta: _wpsc_donation_campaign_post_content': string;
  'Meta: _wpsc_donation_campaign_post_title': string;
  'Meta: _wpsc_donation_campaign_post_author': string;
  'Meta: _wpsc_donation_campaign_post_date': string;
  'Meta: _wpsc_donation_campaign_post_date_gmt': string;
  'Meta: _wpsc_donation_campaign_post_modified': string;
  'Meta: _wpsc_donation_campaign_post_modified_gmt': string;
  'Meta: _wpsc_donation_campaign_post_parent': string;
  'Meta: _wpsc_donation_campaign_post_menu_order': string;
  'Meta: _wpsc_donation_campaign_post_type': string;
  'Meta: _wpsc_donation_campaign_post_mime_type': string;
  'Meta: _wpsc_donation_campaign_post_comment_status': string;
  'Meta: _wpsc_donation_campaign_post_comment_count': string;
  'Meta: _wpsc_donation_campaign_post_ping_status': string;
  'Meta: _wpsc_donation_campaign_post_to_ping': string;
  'Meta: _wpsc_donation_campaign_post_pinged': string;
  'Meta: _wpsc_donation_campaign_post_content_filtered': string;
  'Meta: _wpsc_donation_campaign_post_guid': string;
}

export interface ShopifyData {
  'Handle': string;
  'Title': string;
  'Body (HTML)': string;
  'Vendor': string;
  'Product Category': string;
  'Type': string;
  'Tags': string;
  'Published': string;
  'Option1 Name': string;
  'Option1 Value': string;
  'Option2 Name': string;
  'Option2 Value': string;
  'Option3 Name': string;
  'Option3 Value': string;
  'Variant SKU': string;
  'Variant Grams': string;
  'Variant Inventory Tracker': string;
  'Variant Inventory Qty': string;
  'Variant Inventory Policy': string;
  'Variant Fulfillment Service': string;
  'Variant Price': string;
  'Variant Compare At Price': string;
  'Variant Requires Shipping': string;
  'Variant Taxable': string;
  'Variant Barcode': string;
  'Image Src': string;
  'Image Position': string;
  'Image Alt Text': string;
  'Gift Card': string;
  'SEO Title': string;
  'SEO Description': string;
  'Google Shopping / Google Product Category': string;
  'Google Shopping / Gender': string;
  'Google Shopping / Age Group': string;
  'Google Shopping / MPN': string;
  'Google Shopping / AdWords Grouping': string;
  'Google Shopping / AdWords Labels': string;
  'Google Shopping / Condition': string;
  'Google Shopping / Custom Product': string;
  'Google Shopping / Custom Label 0': string;
  'Google Shopping / Custom Label 1': string;
  'Google Shopping / Custom Label 2': string;
  'Google Shopping / Custom Label 3': string;
  'Google Shopping / Custom Label 4': string;
  'Variant Image': string;
  'Variant Weight Unit': string;
  'Variant Tax Code': string;
  'Cost per item': string;
  'Status': string;
} 